"""initial

Revision ID: 8034c6bf0259
Revises: 
Create Date: 2026-09-09 17:22:37.692253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8034c6bf0259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_activity_type_custom_user_slug', 'activity_types', ['user_id', 'slug'], unique=True, postgresql_where=sa.text('is_system IS false'))
    op.create_index('uq_activity_type_system_slug', 'activity_types', ['slug'], unique=True, postgresql_where=sa.text('is_system IS true'))
    op.create_table('unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('unit_label', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_type_unit_types',
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('per_set', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('activity_type_id', 'unit_type_id'),
    sa.UniqueConstraint('activity_type_id', 'unit_type_id', name='uq_activity_type_unit_type_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_type_unit_types')
    op.drop_table('users')
    op.drop_table('unit_types')
    op.drop_index('uq_activity_type_system_slug', table_name='activity_types', postgresql_where=sa.text('is_system IS true'))
    op.drop_index('uq_activity_type_custom_user_slug', table_name='activity_types', postgresql_where=sa.text('is_system IS false'))
    op.drop_table('activity_types')
    # ### end Alembic commands ###
