"""s301_sessions

Revision ID: f0a07af64e1b
Revises: 8034c6bf0259
Create Date: 2026-09-25 19:56:31.062943

plan_id is added in S3-03.!

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a07af64e1b'
down_revision: Union[str, Sequence[str], None] = '8034c6bf0259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed')", name='ck_workout_sessions_status'),
    sa.CheckConstraint('intensity IS NULL OR intensity BETWEEN 1 AND 10', name='ck_workout_sessions_intensity'),
    sa.ForeignKeyConstraint(['source_session_id'], ['workout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sessions_user_id_session_at', 'workout_sessions', ['user_id', 'session_at'], unique=False)
    op.create_table('workout_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_session_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('planned_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_item_id'], ['workout_session_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_session_measurements')
    op.drop_table('workout_session_items')
    op.drop_index('ix_workout_sessions_user_id_session_at', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
